import type { Chapter } from '../../engine/types'

export const formlar: Chapter = {
  id: 'formlar',
  title: 'Form Uygulamaları',
  subtitle: 'Windows Forms: kontroller, menüler, iletişim kutuları, doğrulama ve veri bağlama',
  unit: 5,
  icon: '🪟',
  color: '#60a5fa',
  levels: [
    {
      id: 'form-1',
      title: 'Form da Bir Sınıftır',
      ref: '5. Öğrenme Birimi',
      cards: [
        {
          icon: '🪟',
          title: 'Görsel arayüzler',
          body: 'Form uygulamaları ile bilgisayar ortamında çalışan **kullanıcı etkileşimli arayüzler** geliştirilir. Windows form sınıfı **System.Windows.Forms** isim uzayı içinde bulunur.',
          code: 'public partial class Form1 : Form\n{\n    public Form1()\n    {\n        InitializeComponent();\n    }\n}',
        },
        {
          icon: '🧬',
          title: 'Kalıtım her yerde',
          body: 'Yukarıdaki koda dikkat et: `Form1 : Form`. Yazdığın her form, hazır **Form** sınıfından **türetilmiş** bir sınıftır! Text, BackColor, Show() gibi yüzlerce üyeyi kalıtım yoluyla devralır.',
        },
      ],
      task: {
        kind: 'quiz',
        question: 'Bir Windows Forms projesinde uygulamanın **hangi formdan başlayacağı** Program.cs dosyasındaki Main içinde hangi metotla belirlenir?',
        options: ['Form.Show()', 'Application.Run()', 'InitializeComponent()', 'Console.ReadLine()', 'Application.Exit()'],
        answer: 1,
        explain: 'Program.cs içindeki Application.Run(new Form1()); satırı uygulamayı Form1 ile başlatır. Başlangıç formunu değiştirmek için bu satırdaki form adı değiştirilir.',
      },
    },
    {
      id: 'form-2',
      title: 'Özellikler, Metotlar, Olaylar',
      ref: '5. Öğrenme Birimi',
      cards: [
        {
          icon: '⚡',
          title: 'Olay (Event)',
          body: 'Kontrollerin **özellikleri** (Text, Size), **metotları** (Show, Hide) ve **olayları** (Click, Load) vardır. Olay; kullanıcı bir butona tıkladığında, form açıldığında veya kapandığında tetiklenir ve ona bağlı metot çalışır.',
        },
      ],
      task: {
        kind: 'match',
        prompt: 'Form sınıfının üyelerini işlevleriyle eşleştir.',
        pairs: [
          { left: 'CenterToScreen()', right: 'Formun ekranın ortasında açılmasını sağlar' },
          { left: 'FormClosed', right: 'Form kapandığında çalışan olaydır' },
          { left: 'ControlBox', right: 'Büyültme, küçültme ve kapatma butonlarını gösterir/gizler' },
          { left: 'Load', right: 'Form açılırken çalışan olaydır' },
          { left: 'AcceptButton', right: 'Enter tuşuna basıldığında belirlenen butonun tıklanmasını sağlar' },
          { left: 'Show()', right: 'Formu göstermek için kullanılan metottur' },
        ],
        explain: 'CenterToScreen ve Show metot, ControlBox ve AcceptButton özellik, Load ve FormClosed ise olaydır.',
      },
    },
    {
      id: 'form-dinamik',
      title: 'Kontrolleri Kodla Üret',
      ref: '5.1.2 · 2. Uygulama',
      cards: [
        {
          icon: '🧱',
          title: 'Her kontrol bir nesnedir',
          body: 'Button, TextBox, Label gibi kontrollerin hepsi **Control** sınıfından türetilmiş sınıflardır. Toolbox\'tan sürükleyip bıraktığın her kontrol aslında bir **nesnedir**. Bu yüzden kontrolleri çalışma anında `new` ile de oluşturabilirsin.',
          code: 'Label lblAdSoyad = new Label();\nTextBox txtAdSoyad = new TextBox();\nButton btnGiris = new Button();',
        },
        {
          icon: '⚡',
          title: 'Özellik ver, olay bağla, forma ekle',
          body: 'Nesnenin özelliklerine değer verilir (`Text`, `Location`, `Size`). Olay metodu **+=** operatörüyle bağlanır. Son olarak kontrol, formun **Controls** koleksiyonuna eklenir. Buradaki `this`, kodun içinde bulunduğu **form nesnesinin kendisidir**.',
          code: 'btnGiris.Click += BtnGiris_Click;\nthis.Controls.Add(btnGiris);',
        },
      ],
      task: {
        kind: 'fill',
        prompt: 'Kitaptaki 2. Uygulamada olduğu gibi bir butonu çalışma anında oluşturup forma ekleyen kodu tamamla.',
        code: 'Button btnGiris = new [[0]]();\n\nprivate void Form1_Load(object sender, EventArgs e)\n{\n    btnGiris.Text = "Tıkla";\n    btnGiris.Location = new [[1]](100, 60);\n    btnGiris.Size = new Size(100, 30);\n    btnGiris.Click [[2]] BtnGiris_Click;\n    this.Controls.[[3]](btnGiris);\n}',
        blanks: [
          { accept: ['Button'], width: 6 },
          { accept: ['Point'], width: 5 },
          { accept: ['+='], width: 2 },
          { accept: ['Add'], width: 3 },
        ],
        explain: 'Button bir sınıftır ve new ile nesnesi üretilir. Konum Point, boyut Size nesnesiyle verilir. += olay metodunu Click olayına bağlar. Controls.Add ise butonu formun kontrol koleksiyonuna ekleyerek görünür yapar.',
      },
    },
    {
      id: 'form-3',
      title: 'Buton Click Olayı',
      ref: '5. Öğrenme Birimi',
      cards: [
        {
          icon: '🖱️',
          title: 'Olay metodu',
          body: 'Tasarım ekranında bir butona çift tıklandığında Visual Studio otomatik olarak bir olay metodu oluşturur. TextBox\'tan gelen veri **string** olduğundan hesaplamadan önce dönüştürülmelidir.',
          code: 'private void button1_Click(object sender, EventArgs e)\n{\n    // butona tıklanınca çalışacak kodlar\n}',
        },
      ],
      task: {
        kind: 'fill',
        prompt: 'TextBox\'a girilen tutarın KDV\'sini (%18) hesaplayıp MessageBox ile gösteren olay metodunu tamamla.',
        code: 'private void button1_Click(object sender, EventArgs e)\n{\n    int sayi;\n    double sonuc;\n    sayi = Convert.[[0]](textBox1.[[1]]);\n    sonuc = sayi * 0.18;\n    MessageBox.[[2]](sonuc.ToString());\n}',
        blanks: [
          { accept: ['ToInt32'], width: 7 },
          { accept: ['Text'], width: 4 },
          { accept: ['Show'], width: 4 },
        ],
        explain: 'textBox1.Text kutudaki yazıyı string olarak verir, Convert.ToInt32 sayıya çevirir. MessageBox.Show metni bir mesaj kutusunda gösterir.',
      },
    },
    {
      id: 'form-4',
      title: 'Hata Avcısı: Metin Kutusu',
      ref: '5. Öğrenme Birimi',
      cards: [
        {
          icon: '🧯',
          title: 'Derleme hatası vs. çalışma hatası',
          body: '**Derleme hatası** varsa program hiç başlamaz (Hata Listesi panelinde görünür). **Çalışma zamanı hatası** ise program çalışırken oluşur; örneğin TextBox\'a "abc" yazılıp Convert.ToInt32 ile çevrilmeye çalışılırsa.',
        },
      ],
      task: {
        kind: 'bug',
        prompt: 'Bu olay metodunda derleme hatası veren satırları bul.',
        code: 'private void btnHesapla_Click(object sender, EventArgs e)\n{\n    int yariCap = textBox1.Text;\n    double piSayisi = 3.14;\n    double alan = piSayisi * yariCap * yariCap;\n    int cevre = 2 * piSayisi * yariCap;\n    MessageBox.Show("Alan: " + alan.ToString());\n}',
        bugLines: [3, 6],
        fix: {
          question: 'Satır 3 için doğru düzeltme hangisidir?',
          options: [
            'int yariCap = textBox1;',
            'int yariCap = Convert.ToInt32(textBox1.Text);',
            'string yariCap = Convert.ToInt32(textBox1.Text);',
            'int yariCap = textBox1.Text.ToString();',
          ],
          answer: 1,
        },
        explain: 'Satır 3: "string türü örtülü olarak int türüne dönüştürülemez." Satır 6: double ile yapılan çarpımın sonucu double\'dır; int değişkene açık dönüşüm olmadan atanamaz (cevre double olmalı).',
      },
    },
    {
      id: 'form-5',
      title: 'Dairenin Alanı',
      ref: '5. Öğrenme Birimi',
      cards: [
        {
          icon: '⭕',
          title: 'Adım adım',
          body: 'Bir olay metodunda işlemler mantıklı bir sırayla yapılmalıdır: önce **değişkenler tanımlanır**, sonra **girdiler okunur ve dönüştürülür**, ardından **hesaplama** yapılır ve en son **sonuç gösterilir**.',
        },
      ],
      task: {
        kind: 'order',
        prompt: 'Dairenin alanını ve çevresini hesaplayan buton olayının satırlarını doğru sıraya diz.',
        lines: [
          'private void button1_Click(object sender, EventArgs e)',
          '{',
          '    int yariCap;',
          '    double alan, cevre, piSayisi;',
          '    piSayisi = 3.14;',
          '    yariCap = Convert.ToInt32(textBox1.Text);',
          '    alan = piSayisi * yariCap * yariCap;',
          '    cevre = 2 * piSayisi * yariCap;',
          '    MessageBox.Show("Dairenin alanı=" + alan.ToString());',
          '    MessageBox.Show("Dairenin çevresi=" + cevre.ToString());',
          '}',
        ],
        alternatives: [
          [
            'private void button1_Click(object sender, EventArgs e)',
            '{',
            '    double alan, cevre, piSayisi;',
            '    int yariCap;',
            '    piSayisi = 3.14;',
            '    yariCap = Convert.ToInt32(textBox1.Text);',
            '    alan = piSayisi * yariCap * yariCap;',
            '    cevre = 2 * piSayisi * yariCap;',
            '    MessageBox.Show("Dairenin alanı=" + alan.ToString());',
            '    MessageBox.Show("Dairenin çevresi=" + cevre.ToString());',
            '}',
          ],
        ],
        explain: 'Değişken kullanılmadan önce tanımlanmalı, hesaplamada kullanılmadan önce de değer almalıdır. Sonuçlar hesaplandıktan sonra gösterilir.',
      },
    },
    {
      id: 'form-konteyner',
      title: 'Konteyner Kontrolleri',
      ref: '5.1.3',
      cards: [
        {
          icon: '🗂️',
          title: 'Kontrolleri gruplamak',
          body: 'Formda çok fazla kontrol olursa görüntü karmaşıklaşır. **Konteyner kontroller** ilişkili kontrolleri bir arada tutar: **Panel**, **GroupBox**, **TabControl**, **FlowLayoutPanel**, **SplitContainer**. Konteynerin Enabled veya Visible özelliği değişince içindeki tüm kontroller de etkilenir.',
        },
        {
          icon: '📦',
          title: 'Hangisi ne işe yarar?',
          body: '**GroupBox**: Formu bölümlere ayırır (ör. bilgisayar fiyat hesaplama). **Panel**: GroupBox gibidir ama **kaydırma çubuğu** olabilir (AutoScroll). **TabControl**: Kontrolleri **sekme sayfalarında** gösterir (Müşteri, Sipariş, Hesap sekmeleri).',
        },
      ],
      task: {
        kind: 'quiz',
        question: 'Aşağıdakilerden hangisi Toolbox penceresi içindeki **Containers** sekmesinde **bulunmaz**?',
        options: ['GroupBox', 'Panel', 'TabControl', 'SplitContainer', 'WebBrowser'],
        answer: 4,
        explain: 'WebBrowser bir konteyner değil, web sayfalarını gösteren bir kontroldür. Kitaptaki 4. Uygulamada WebBrowser, bir Panel konteynerinin içine yerleştirilir.',
      },
    },
    {
      id: 'form-menu',
      title: 'Menüler ve İletişim Kutuları',
      ref: '5.2 – 5.3',
      cards: [
        {
          icon: '📋',
          title: 'Menüler',
          body: '**MenuStrip** uygulamanın üst kısmındaki menüleri (Dosya, Düzen, Çıkış) oluşturur. **ContextMenuStrip** ise sağ tıklandığında açılan menüdür. Menü elemanlarına **ShortcutKeys** ile kısayol (Ctrl+C, Ctrl+V…) atanabilir.',
          code: 'private void menuKopyala_Click(object sender, EventArgs e)\n{\n    txtEditor.Copy();\n}',
        },
        {
          icon: '💬',
          title: 'İletişim kutuları (Dialog Boxes)',
          body: 'Kullanıcı ile uygulama arasında iletişimi sağlayan pencerelerdir ve yeniden boyutlandırılamazlar. **SaveFileDialog** ve **OpenFileDialog** dosyayı kaydetmez ya da açmaz; yalnızca **konumunu ve adını** belirler. İşlemi yapan RichTextBox\'ın SaveFile() / LoadFile() metotlarıdır.',
        },
      ],
      task: {
        kind: 'match',
        prompt: 'Kontrolleri görevleriyle eşleştir.',
        pairs: [
          { left: 'MenuStrip', right: 'Formun üst kısmında menü ve alt menüler oluşturur' },
          { left: 'ContextMenuStrip', right: 'Sağ tıklandığında açılan menüyü oluşturur' },
          { left: 'SaveFileDialog', right: 'Kaydedilecek dosyanın konumunu ve adını belirler' },
          { left: 'OpenFileDialog', right: 'Açılacak dosyanın seçilmesini sağlar' },
          { left: 'FontDialog', right: 'Yazı tipi ve boyutunun seçilmesini sağlar' },
          { left: 'ColorDialog', right: 'Renk paletinden renk seçilmesini sağlar' },
        ],
        explain: 'Diyalog kutuları seçim yapmayı sağlar; asıl işi (kaydetme, açma, yazdırma) başka nesneler yapar. Örneğin yazdırma işlemini PrintDialog değil PrintDocument nesnesinin Print() metodu gerçekleştirir.',
      },
    },
    {
      id: 'form-7',
      title: 'Mesaj Kutusu (MessageBox)',
      ref: '5.3.1',
      cards: [
        {
          icon: '💬',
          title: 'MessageBox.Show parametreleri',
          body: 'MessageBox.Show metodunun parametre sırası: **mesaj**, **başlık**, **butonlar** (MessageBoxButtons.YesNo, OKCancel, YesNoCancel…) ve **simge** (MessageBoxIcon.Error, Warning, Information…).',
          code: 'MessageBox.Show("Kayıt silinsin mi?", "Onay",\n    MessageBoxButtons.YesNo, MessageBoxIcon.Warning);',
        },
      ],
      task: {
        kind: 'quiz',
        question: 'Başlığı "Uyarı", mesajı "Dosya kaydedilsin mi?" olan; **Evet / Hayır / İptal** butonları ve **uyarı** simgesi içeren mesaj kutusu hangisiyle oluşturulur?',
        options: [
          'MessageBox.Show("Uyarı", "Dosya kaydedilsin mi?", MessageBoxButtons.YesNoCancel, MessageBoxIcon.Warning);',
          'MessageBox.Show("Dosya kaydedilsin mi?", "Uyarı", MessageBoxButtons.YesNo, MessageBoxIcon.Error);',
          'MessageBox.Show("Dosya kaydedilsin mi?", "Uyarı", MessageBoxButtons.YesNoCancel, MessageBoxIcon.Warning);',
          'MessageBox.Show("Dosya kaydedilsin mi?", "Uyarı", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);',
          'MessageBox.Show("Uyarı", MessageBoxButtons.YesNoCancel, "Dosya kaydedilsin mi?");',
        ],
        answer: 2,
        explain: 'İlk parametre mesaj, ikincisi başlıktır. Evet/Hayır/İptal için YesNoCancel, uyarı simgesi için MessageBoxIcon.Warning kullanılır.',
      },
    },
    {
      id: 'form-dialog',
      title: 'Kullanıcının Cevabı: DialogResult',
      ref: '5.3.1',
      cards: [
        {
          icon: '❔',
          title: 'Hangi butona tıklandı?',
          body: 'MessageBox.Show() ve diyalogların ShowDialog() metodu, kullanıcının tıkladığı butonu **DialogResult** türünde döndürür. Bu değer if ile kontrol edilerek programın ne yapacağına karar verilir.',
          code: 'DialogResult cevap = sfd.ShowDialog();\nif (cevap == DialogResult.OK)\n{\n    txtEditor.SaveFile(sfd.FileName, RichTextBoxStreamType.PlainText);\n}',
        },
      ],
      task: {
        kind: 'fill',
        prompt: 'Kitaptaki örnekte olduğu gibi, kullanıcıya Evet/Hayır butonlu bir uyarı mesajı gösterip cevabını kontrol eden kodu tamamla.',
        code: '[[0]] cevap = MessageBox.Show("Bu dosyayı silmek istediğinize emin misiniz?", "Dosya Sil",\n    MessageBoxButtons.[[1]], MessageBoxIcon.Warning);\n\nif (cevap == DialogResult.[[2]])\n{\n    MessageBox.Show("Dosya silindi.");\n}\nelse if (cevap == DialogResult.No)\n{\n    MessageBox.Show("İşlem iptal edildi.");\n}',
        blanks: [
          { accept: ['DialogResult'], width: 12 },
          { accept: ['YesNo'], width: 5 },
          { accept: ['Yes'], width: 3 },
        ],
        explain: 'MessageBox.Show bir DialogResult değeri döndürür. YesNo, Evet ve Hayır butonlarını gösterir; Evet\'e tıklanırsa sonuç DialogResult.Yes olur.',
      },
    },
    {
      id: 'form-mask',
      title: 'Veri Girişi Maskeleme',
      ref: '5.4.3 · 18. Uygulama',
      cards: [
        {
          icon: '🎭',
          title: 'MaskedTextBox',
          body: 'MaskedTextBox, verinin **belirlenen formatta** girilmesini sağlar (TC kimlik no, telefon, tarih…). Mask özelliğindeki karakterler:\n`0` rakam (zorunlu) • `9` rakam veya boşluk (isteğe bağlı) • `#` rakam, boşluk, +/- • `L` harf (zorunlu) • `?` harf (isteğe bağlı) • `A` harf veya rakam (zorunlu) • `$` para birimi • `>` büyük harfe çevirir • `<` küçük harfe çevirir',
          code: 'maskTC.Mask = "00000000000";\nmaskTelefon.Mask = "(999) 000 00 00";\nmaskTarih.Mask = "00/00/0000";',
        },
      ],
      task: {
        kind: 'quiz',
        question: 'I. Girilmesi zorunlu rakamlar için kullanılır.\nII. Para birimi işareti için kullanılır.\nIII. Tüm karakterleri büyük harfe çevirir.\nIV. Girilmesi zorunlu harfler için kullanılır.\nMaskedTextBox maskeleme karakterleri için **doğru sıralama** hangisidir?',
        options: ['#, $, <, L', '9, $, <, A', '0, $, <, a', '0, $, >, L', '9, $, >, A'],
        answer: 3,
        explain: '0 zorunlu rakam, $ para birimi, > tüm karakterleri büyük harfe çevirir, L zorunlu harftir. (9 isteğe bağlı rakam, A harf veya rakam, < küçük harfe çevirir.)',
      },
    },
    {
      id: 'form-dogrulama',
      title: 'Veri Doğrulama (Validating)',
      ref: '5.4.2 · 17. Uygulama',
      cards: [
        {
          icon: '🛡️',
          title: 'Hatalı veriye geçit yok',
          body: 'Ders notu 100 olan öğrenciye yanlışlıkla 1000 girilirse ortalama bozulur; rakam yerine harf girilirse program hata verir. Bu yüzden veriler **doğrulanmalıdır**. TextBox\'ın **Validating** olayı, kontrolden çıkılırken çalışır. `e.Cancel = true` kullanıcının kutudan ayrılmasını engeller; **ErrorProvider** kutunun yanında uyarı simgesi gösterir.',
          code: 'ErrorProvider ep = new ErrorProvider();\n\nif (int.TryParse(txtNumara.Text, out int sonuc))\n    ep.SetError(txtNumara, "");\nelse\n{\n    e.Cancel = true;\n    ep.SetError(txtNumara, "Numara girişi hatalı");\n}',
        },
        {
          icon: '🔁',
          title: 'Kapsüllemeyle bağlantı',
          body: 'Bu, Kapsülleme bölümündeki **set bloğunda doğrulama** fikrinin form karşılığıdır: geçersiz değerin içeri girmesine izin verilmez. `int.TryParse` metni sayıya çevirmeyi dener; başarılıysa true döndürür ve sonucu `out` ile verir. Convert.ToInt32\'nin aksine hata fırlatmaz.',
        },
      ],
      task: {
        kind: 'code',
        prompt: 'Kitaptaki 17. Uygulamanın 5. adımını yaz: `txtDersNotu_Validating(object sender, CancelEventArgs e)` olayında girilen değer **sayısal değilse** veya **0–100 aralığında değilse** `e.Cancel = true` yap ve `ep.SetError` ile uyar. Değer geçerliyse hatayı temizle (`ep.SetError(txtDersNotu, "")`).',
        starter: 'public partial class Form1 : Form\n{\n    ErrorProvider ep = new ErrorProvider();\n\n    private void txtDersNotu_Validating(object sender, CancelEventArgs e)\n    {\n        int dersNotu;\n\n    }\n}\n',
        solution: 'public partial class Form1 : Form\n{\n    ErrorProvider ep = new ErrorProvider();\n\n    private void txtDersNotu_Validating(object sender, CancelEventArgs e)\n    {\n        int dersNotu;\n        if (int.TryParse(txtDersNotu.Text, out dersNotu))\n        {\n            if (dersNotu < 0 || dersNotu > 100)\n            {\n                e.Cancel = true;\n                ep.SetError(txtDersNotu, "0-100 arasında değer giriniz.");\n            }\n            else\n            {\n                ep.SetError(txtDersNotu, "");\n            }\n        }\n        else\n        {\n            e.Cancel = true;\n            ep.SetError(txtDersNotu, "Sayısal değer giriniz.");\n        }\n    }\n}\n',
        rules: [
          { t: 'method', goal: 'txtDersNotu_Validating(object sender, CancelEventArgs e) olay metodu', cls: 'Form1', name: 'txtDersNotu_Validating', params: ['object', 'CancelEventArgs'] },
          { t: 'source', goal: 'int.TryParse ile değerin sayısal olup olmadığını kontrol et', regex: 'int\\.TryParse\\s*\\(\\s*txtDersNotu\\.Text\\s*,\\s*out\\s+(int\\s+)?\\w+\\s*\\)' },
          { t: 'source', goal: 'Notun 0–100 aralığında olup olmadığını kontrol et', regex: '(<\\s*0|>=\\s*0|0\\s*>|0\\s*<=)[\\s\\S]*(>\\s*100|<=\\s*100|100\\s*<|100\\s*>=)|(>\\s*100|<=\\s*100|100\\s*<|100\\s*>=)[\\s\\S]*(<\\s*0|>=\\s*0|0\\s*>|0\\s*<=)' },
          { t: 'method', goal: 'Hatalı girişte e.Cancel = true yap ve ep.SetError ile uyar', cls: 'Form1', name: 'txtDersNotu_Validating', bodyHas: ['e.Cancel = true;', 'ep.SetError(txtDersNotu,'] },
          { t: 'method', goal: 'Geçerli girişte hatayı temizle', cls: 'Form1', name: 'txtDersNotu_Validating', bodyHas: ['ep.SetError(txtDersNotu, "");'] },
        ],
        explain: 'İki aşamalı doğrulama yapıldı: önce TryParse ile türün (sayı mı?), sonra aralığın (0–100) kontrolü. e.Cancel = true, kullanıcı doğru değeri girene kadar odağın kutudan çıkmasını engeller.',
      },
      hints: ['if (int.TryParse(txtDersNotu.Text, out dersNotu)) { ... } else { ... }', 'if (dersNotu < 0 || dersNotu > 100) { e.Cancel = true; ep.SetError(txtDersNotu, "..."); }'],
    },
    {
      id: 'form-6',
      title: 'Liste ile Veri Bağlama',
      ref: '5. Öğrenme Birimi · 24. Uygulama',
      cards: [
        {
          icon: '🔗',
          title: 'DataGridView + List<T>',
          body: 'Ders kitabındaki 24. uygulamada öğrenci bilgileri `Ogrenciler` sınıfından üretilen nesnelerle bir **List<Ogrenciler>** koleksiyonuna eklenir. Liste, DataGridView kontrolünün **DataSource** özelliğine atanarak tabloda gösterilir (**kompleks veri bağlama**).',
          code: 'List<Ogrenciler> liste = new List<Ogrenciler>();\n\nprivate void Bagla()\n{\n    gridListe.DataSource = null;\n    gridListe.DataSource = liste;\n}',
        },
      ],
      task: {
        kind: 'code',
        prompt: 'Kitaptaki uygulamayı tamamla: `btnEkle_Click` olayında yeni bir **Ogrenciler** nesnesi oluştur, TextBox\'lardan gelen değerleri **Numara**, **AdSoyad** ve **DersNotu** özelliklerine aktar, nesneyi listeye **Add** ile ekle ve **Bagla()** metodunu çağır.',
        starter: 'class Ogrenciler\n{\n    public int Numara { get; set; }\n    public string AdSoyad { get; set; }\n    public int DersNotu { get; set; }\n}\n\npublic partial class Form1 : Form\n{\n    List<Ogrenciler> liste = new List<Ogrenciler>();\n\n    private void btnEkle_Click(object sender, EventArgs e)\n    {\n\n    }\n\n    private void Bagla()\n    {\n        gridListe.DataSource = null;\n        gridListe.DataSource = liste;\n    }\n}\n',
        solution: 'class Ogrenciler\n{\n    public int Numara { get; set; }\n    public string AdSoyad { get; set; }\n    public int DersNotu { get; set; }\n}\n\npublic partial class Form1 : Form\n{\n    List<Ogrenciler> liste = new List<Ogrenciler>();\n\n    private void btnEkle_Click(object sender, EventArgs e)\n    {\n        Ogrenciler ogrenci = new Ogrenciler();\n        ogrenci.Numara = int.Parse(txtNumara.Text);\n        ogrenci.AdSoyad = txtAdSoyad.Text;\n        ogrenci.DersNotu = int.Parse(txtDersNotu.Text);\n        liste.Add(ogrenci);\n        Bagla();\n    }\n\n    private void Bagla()\n    {\n        gridListe.DataSource = null;\n        gridListe.DataSource = liste;\n    }\n}\n',
        rules: [
          { t: 'new', goal: 'Yeni bir Ogrenciler nesnesi oluştur', type: 'Ogrenciler' },
          { t: 'source', goal: 'Numara özelliğine txtNumara değerini sayıya çevirerek aktar', regex: '\\.Numara\\s*=\\s*(int\\.Parse|Convert\\.ToInt32)\\s*\\(\\s*txtNumara\\.Text\\s*\\)' },
          { t: 'source', goal: 'AdSoyad özelliğine txtAdSoyad.Text değerini aktar', regex: '\\.AdSoyad\\s*=\\s*txtAdSoyad\\.Text' },
          { t: 'source', goal: 'DersNotu özelliğine txtDersNotu değerini sayıya çevirerek aktar', regex: '\\.DersNotu\\s*=\\s*(int\\.Parse|Convert\\.ToInt32)\\s*\\(\\s*txtDersNotu\\.Text\\s*\\)' },
          { t: 'method', goal: 'Nesneyi listeye ekle ve Bagla() metodunu çağır', cls: 'Form1', name: 'btnEkle_Click', bodyHas: ['liste.Add(', 'Bagla();'] },
        ],
        explain: 'DataSource önce null yapılıp sonra tekrar listeye atanır; böylece DataGridView listedeki yeni elemanları gösterecek şekilde yenilenir. int.Parse da Convert.ToInt32 gibi metni sayıya çevirir.',
      },
      hints: ['Ogrenciler ogrenci = new Ogrenciler();', 'ogrenci.Numara = int.Parse(txtNumara.Text);', 'liste.Add(ogrenci); Bagla();'],
    },
    {
      id: 'form-bagla',
      title: 'Basit ve Kompleks Veri Bağlama',
      ref: '5.5',
      cards: [
        {
          icon: '🔗',
          title: 'Basit veri bağlama',
          body: 'Bir kontrole **tek bir veri** bağlanır. **Binding** sınıfından nesne üretilir; üç parametre alır: **propertyName** (kontrolün hangi özelliği), **dataSource** (veri kaynağı nesnesi), **dataMember** (kaynağın hangi özelliği). Kaynak, kendi yazdığın bir sınıfın nesnesi olabilir!',
          code: 'Ogrenciler ogrenci = new Ogrenciler();\nogrenci.AdSoyad = "Mert";\ntxtAdSoyad.DataBindings.Add("Text", ogrenci, "AdSoyad");',
        },
        {
          icon: '📚',
          title: 'Kompleks veri bağlama',
          body: 'Bir kontrole **birden çok veri** bağlanır: ListBox, ComboBox, DataGridView. Kontrolün **DataSource** özelliğine dizi, ArrayList, List<T> veya DataTable atanır. **DisplayMember** gösterilecek özelliği, **ValueMember** arka planda tutulacak değeri belirler.',
          code: 'cbSehirler.DataSource = listSehirler;\ncbSehirler.DisplayMember = "SehirAdi";\ncbSehirler.ValueMember = "Plaka";',
        },
      ],
      task: {
        kind: 'quiz',
        question: 'I. Tek veri için basit veri bağlama kullanılır.\nII. Birden çok veri için kompleks veri bağlama kullanılır.\nIII. Basit veri bağlama için Binding sınıfından üretilen nesne kullanılır.\nIV. ComboBox kontrolü kompleks veri bağlama için uygun değildir.\nV. Kompleks veri bağlamada kontrolün DataSource özelliği kullanılır.\nYukarıdaki bilgilerden **hangileri doğrudur**?',
        options: ['I-II', 'I-II-III', 'I-II-V', 'I-II-III-IV', 'I-II-III-V'],
        answer: 4,
        explain: 'IV yanlıştır: ComboBox, ListBox ve DataGridView kompleks veri bağlamada en çok kullanılan kontrollerdir. Diğer tüm ifadeler doğrudur.',
      },
    },
    {
      id: 'form-combo',
      title: 'Bölüm Sonu: Şehirler ComboBox\'ı',
      boss: true,
      xp: 25,
      ref: '5.5.2 · 23. Uygulama',
      cards: [
        {
          icon: '🏙️',
          title: 'Nesneler arayüzde',
          body: 'Bu görevde nesne tabanlı programlama ile form uygulamasını birleştireceksin: bir sınıf tasarla, nesnelerini bir **List<T>** koleksiyonunda topla ve bu listeyi bir **ComboBox**\'a bağla. Kullanıcı şehir adını görür, program arka planda plakayı (ValueMember) kullanır.',
        },
      ],
      task: {
        kind: 'code',
        prompt: 'Kitaptaki 23. Uygulamayı tamamla:\n1) `Sehirler` sınıfına `string Plaka` ve `string SehirAdi` otomatik özelliklerini ekle.\n2) Form1 içinde `List<Sehirler> listSehirler` koleksiyonunu oluştur.\n3) `btnEkle_Click` içinde yeni bir Sehirler nesnesi oluştur, txtPlaka ve txtSehirAdi değerlerini aktar, listeye ekle ve `Bagla()` metodunu çağır.\n4) `Bagla()` metodunda cbSehirler\'in DataSource\'unu önce null, sonra listSehirler yap; DisplayMember = "SehirAdi", ValueMember = "Plaka" olsun.',
        starter: 'class Sehirler\n{\n\n}\n\npublic partial class Form1 : Form\n{\n    // List koleksiyonunu oluştur\n\n    private void btnEkle_Click(object sender, EventArgs e)\n    {\n\n    }\n\n    private void Bagla()\n    {\n\n    }\n}\n',
        solution: 'class Sehirler\n{\n    public string Plaka { get; set; }\n    public string SehirAdi { get; set; }\n}\n\npublic partial class Form1 : Form\n{\n    List<Sehirler> listSehirler = new List<Sehirler>();\n\n    private void btnEkle_Click(object sender, EventArgs e)\n    {\n        Sehirler sehir = new Sehirler();\n        sehir.Plaka = txtPlaka.Text;\n        sehir.SehirAdi = txtSehirAdi.Text;\n        listSehirler.Add(sehir);\n        Bagla();\n    }\n\n    private void Bagla()\n    {\n        cbSehirler.DataSource = null;\n        cbSehirler.DataSource = listSehirler;\n        cbSehirler.DisplayMember = "SehirAdi";\n        cbSehirler.ValueMember = "Plaka";\n    }\n}\n',
        rules: [
          { t: 'property', goal: 'Sehirler: public string Plaka { get; set; }', cls: 'Sehirler', name: 'Plaka', type: 'string', access: 'public', get: true, set: true },
          { t: 'property', goal: 'Sehirler: public string SehirAdi { get; set; }', cls: 'Sehirler', name: 'SehirAdi', type: 'string', access: 'public', get: true, set: true },
          { t: 'field', goal: 'Form1 içinde List<Sehirler> listSehirler koleksiyonu', cls: 'Form1', name: 'listSehirler', type: 'List<Sehirler>' },
          { t: 'new', goal: 'btnEkle_Click içinde yeni bir Sehirler nesnesi oluştur', type: 'Sehirler' },
          { t: 'method', goal: 'Değerleri aktar, listeye ekle ve Bagla() çağır', cls: 'Form1', name: 'btnEkle_Click', bodyHas: ['.Plaka = txtPlaka.Text;', '.SehirAdi = txtSehirAdi.Text;', 'listSehirler.Add(', 'Bagla();'] },
          { t: 'method', goal: 'Bagla(): DataSource önce null, sonra listSehirler', cls: 'Form1', name: 'Bagla', bodyHas: ['cbSehirler.DataSource = null;', 'cbSehirler.DataSource = listSehirler;'] },
          { t: 'method', goal: 'Bagla(): DisplayMember = "SehirAdi", ValueMember = "Plaka"', cls: 'Form1', name: 'Bagla', bodyHas: ['cbSehirler.DisplayMember = "SehirAdi";', 'cbSehirler.ValueMember = "Plaka";'] },
        ],
        explain: 'DataSource önce null yapılır çünkü aynı liste nesnesi tekrar atandığında ComboBox değişikliği fark etmez; null ataması bağlantıyı sıfırlayıp listeyi yeniden okutur. DisplayMember kullanıcıya gösterilen, ValueMember ise cbSehirler.SelectedValue ile okunan özelliktir.',
      },
      hints: ['List<Sehirler> listSehirler = new List<Sehirler>();', 'Sehirler sehir = new Sehirler(); sehir.Plaka = txtPlaka.Text; ...', 'cbSehirler.DisplayMember = "SehirAdi";'],
    },
  ],
}
